
SUBROUTINE MAKING_OBSTACLE(ERROR,OBST,NODID,OBSCOUNT,OBSCOORD,LX,LY)

IMPLICIT NONE
     
INTEGER  LX,LY,OBSCOUNT,IO,IOSTAT,OBSCOORD(1000,2),NODID(LX,LY)  
LOGICAL  ERROR,OBST(LX,LY)
INTEGER  X,Y,I,J,INCX,INCY,OBSNUM,K !.....local variables


OPEN(10,file='SALSAM.OBS')

WRITE(*,*) "ENTER K"
READ(*,*) K
!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@2


INCX=INT(LX/20.)
INCY=INT(LY/10.)

IF (K==1) THEN


DO  I=1,LX
	
	WRITE(10,*) I,1		
	OBST(I,1) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=1
	NODID(I,1)=2

	WRITE(10,*)I,LY	
	OBST(I,LY) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=LY
	NODID(I,LY)=2

END DO


DO  I=2,LY-1
	
	WRITE(10,*) 1,I		
	OBST(1,I) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=1   
	OBSCOORD(OBSCOUNT,2)=I
	NODID(1,I)=2

	WRITE(10,*) LX,I		
	OBST(LX,I) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=LX   
	OBSCOORD(OBSCOUNT,2)=I
	NODID(1,I)=2


END DO



ELSE IF(K==2)  THEN



DO  I=(4*INCX+1),(6*INCX)
	
	WRITE(10,*) I,4*INCY+1		
	OBST(I,4*INCY+1) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=4*INCY+1
	NODID(I,4*INCY+1)=2

	WRITE(10,*) I,6*INCY		
	OBST(I,6*INCY) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=6*INCY
	NODID(I,6*INCY)=2

END DO

DO  J=(4*INCY+2),(6*INCY-1)

	WRITE(10,*) (4*INCX+1),J		
	OBST((4*INCX+1),J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=(4*INCX+1)   
	OBSCOORD(OBSCOUNT,2)=J
	NODID((4*INCX+1),J)=2

	WRITE(10,*) (6*INCX),J		
	OBST(6*INCX,J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=6*INCX   
	OBSCOORD(OBSCOUNT,2)=J
	NODID(6*INCX,J)=2

END DO



DO  I=(INCX+1),(3*INCX)
	
	WRITE(10,*) I,7*INCY+1		
	OBST(I,7*INCY+1) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=7*INCY+1
	NODID(I,7*INCY+1)=2

	WRITE(10,*) I,9*INCY		
	OBST(I,9*INCY) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=9*INCY
	NODID(I,9*INCY)=2

END DO

DO  J=(7*INCY+2),(9*INCY-1)

	WRITE(10,*) (INCX+1),J		
	OBST((INCX+1),J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=(INCX+1)   
	OBSCOORD(OBSCOUNT,2)=J
	NODID((INCX+1),J)=2

	WRITE(10,*) (3*INCX),J		
	OBST(3*INCX,J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=3*INCX   
	OBSCOORD(OBSCOUNT,2)=J
	NODID(3*INCX,J)=2

END DO

DO  I=(INCX+1),(3*INCX)
	
	WRITE(10,*) I,INCY+1		
	OBST(I,INCY+1) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=INCY+1
	NODID(I,5*INCY+1)=2

	WRITE(10,*) I,3*INCY		
	OBST(I,3*INCY) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=3*INCY
	NODID(I,3*INCY)=2

END DO

DO  J=(INCY+2),(3*INCY-1)

	WRITE(10,*) (INCX+1),J		
	OBST((INCX+1),J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=(INCX+1)   
	OBSCOORD(OBSCOUNT,2)=J
	NODID((INCX+1),J)=2

	WRITE(10,*) (3*INCX),J		
	OBST(3*INCX,J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=3*INCX   
	OBSCOORD(OBSCOUNT,2)=J
	NODID(3*INCX,J)=2

END DO










DO  I=(7*INCX+1),(9*INCX)
	
	WRITE(10,*) I,7*INCY+1		
	OBST(I,7*INCY+1) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=7*INCY+1
	NODID(I,7*INCY+1)=2

	WRITE(10,*) I,9*INCY		
	OBST(I,9*INCY) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=9*INCY
	NODID(I,9*INCY)=2

END DO

DO  J=(7*INCY+2),(9*INCY-1)

	WRITE(10,*) (7*INCX+1),J		
	OBST((7*INCX+1),J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=(7*INCX+1)   
	OBSCOORD(OBSCOUNT,2)=J
	NODID((7*INCX+1),J)=2

	WRITE(10,*) (9*INCX),J		
	OBST(9*INCX,J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=9*INCX   
	OBSCOORD(OBSCOUNT,2)=J
	NODID(9*INCX,J)=2

END DO

DO  I=(7*INCX+1),(9*INCX)
	
	WRITE(10,*) I,INCY+1		
	OBST(I,INCY+1) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=INCY+1
	NODID(I,5*INCY+1)=2

	WRITE(10,*) I,3*INCY		
	OBST(I,3*INCY) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=I   
	OBSCOORD(OBSCOUNT,2)=3*INCY
	NODID(I,3*INCY)=2

END DO

DO  J=(INCY+2),(3*INCY-1)

	WRITE(10,*) (7*INCX+1),J		
	OBST((7*INCX+1),J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=(7*INCX+1)   
	OBSCOORD(OBSCOUNT,2)=J
	NODID((7*INCX+1),J)=2

	WRITE(10,*) (9*INCX),J		
	OBST(9*INCX,J) = .TRUE.  !.......defIne OBSTACLE
	OBSCOUNT=OBSCOUNT+1
	OBSCOORD(OBSCOUNT,1)=9*INCX   
	OBSCOORD(OBSCOUNT,2)=J
	NODID(9*INCX,J)=2

END DO



END IF
!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@











!WRITE(6,*) '%%%%%%%%%%  HOW MANY OBSTACLE? %%%%%%%%%%%%%%%%%'

!READ(6,*) OBSNUM


!obsnum=5

!INCX=INT(0.5*LX/(1.*OBSNUM))

!INCY=INT(LY/4.)


!DO Y = 1, LY                           !.....no OBSTACLEs in OBSTACLE arraY  
 !   DO X = 1, LX

  !    OBST(X,Y) = .FALSE.

!	END DO
!END DO

!OBSCOUNT=0;

!DO  I=1,OBSNUM-1
	
!	DO  J=1,INCX
		
!		WRITE(10,*) (I-1)*2*INCX +(J-1)+INT(1.5*INCX),20		
!		OBST((I-1)*2*INCX +(J-1)+INT(1.5*INCX),20) = .TRUE.  !.......defIne OBSTACLE
!		OBSCOUNT=OBSCOUNT+1
!		OBSCOORD(OBSCOUNT,1)=(I-1)*2*INCX +(J-1)+INT(1.5*INCX)   
!		OBSCOORD(OBSCOUNT,2)=20
!		NODID((I-1)*2*INCX +(J-1)+INT(1.5*INCX),20)=2
		
!		WRITE(10,*) (I-1)*2*INCX +(J-1)+INT(1.5*INCX),20+INCY
!		OBST((I-1)*2*INCX +(J-1)+INT(1.5*INCX),20+INCY) = .TRUE.  !.......define OBSTACLE
!		OBSCOUNT=OBSCOUNT+1
!		OBSCOORD(OBSCOUNT,1)=(I-1)*2*INCX +(J-1)+INT(1.5*INCX)   
!		OBSCOORD(OBSCOUNT,2)=20+INCY
!		NODID((I-1)*2*INCX +(J-1)+INT(1.5*INCX),20+INCY)=2


!	END DO
	
!	DO  J=1,INCY-1
	
!		WRITE(10,*) (I-1)*2*INCX+INT(1.5*INCX),20+J
!		OBST((I-1)*2*INCX +INT(1.5*INCX),20+J) = .TRUE.  !.......define OBSTACLE
!!		OBSCOUNT=OBSCOUNT+1
!		OBSCOORD(OBSCOUNT,1)=(I-1)*2*INCX+INT(1.5*INCX)  
!		OBSCOORD(OBSCOUNT,2)=20+J
!		NODID((I-1)*2*INCX+INT(1.5*INCX),20+J)=2
!		
!		WRITE(10,*) (I-1)*2*INCX +(INCX-1)+INT(1.5*INCX),20+J
!		OBST((I-1)*2*INCX +(INCX-1)+INT(1.5*INCX),20+J) = .TRUE.  !.......define OBSTACLE
!		OBSCOUNT=OBSCOUNT+1
!		OBSCOORD(OBSCOUNT,1)=(I-1)*2*INCX +(INCX-1)+INT(1.5*INCX)   
!		OBSCOORD(OBSCOUNT,2)=20+J
!		NODID((I-1)*2*INCX +(INCX-1)+INT(1.5*INCX),20+J)=2
!
!	END DO
	
!END DO

!DO  J=1,LX
		
!		WRITE(10,*) J,1		
!		OBST(J,1) = .TRUE.  !.......defIne OBSTACLE
!		OBSCOUNT=OBSCOUNT+1
!		OBSCOORD(OBSCOUNT,1)=J   
!		OBSCOORD(OBSCOUNT,2)=20
!		NODID(J,1)=2
		
!		WRITE(10,*) J,LY
!		OBST(J,LY) = .TRUE.  !.......define OBSTACLE
!		OBSCOUNT=OBSCOUNT+1
!!		OBSCOORD(OBSCOUNT,1)=J   
!		OBSCOORD(OBSCOUNT,2)=LY
!		NODID(J,LY)=2


!END DO


CLOSE(10)


RETURN
END