
SUBROUTINE OUTFLOW(N_HELP,LX,LY,RO)

IMPLICIT NONE

INTEGER  LX,LY
REAL*8  RO,RU,UX,FEQ1,FEQ2,N_HELP(0:8,LX,LY)
INTEGER  X,Y  !.....local variables


DO  Y=2,LY-1
	
	FEQ1=N_HELP(0,LX,Y)+N_HELP(2,LX,Y)+N_HELP(4,LX,Y)
	FEQ2=N_HELP(1,LX,Y)+N_HELP(5,LX,Y)+N_HELP(8,LX,Y)
	UX=-1.+(FEQ1+2.*FEQ2)/(RO)
	RU=RO*UX
	N_HELP(3,LX,Y)=N_HELP(1,LX,Y)-(2./3.)*RU
	N_HELP(7,LX,Y)=N_HELP(5,LX,Y)-(1./6.)*RU+(1./2.)*(N_HELP(2,LX,Y)-N_HELP(4,LX,Y))
	N_HELP(6,LX,Y)=N_HELP(8,LX,Y)-(1./6.)*RU-(1./2.)*(N_HELP(2,LX,Y)-N_HELP(4,LX,Y))

END DO

RETURN
END